# Generated by Django 4.2.6 on 2024-01-07 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_topcompanies_interviewquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('companyIdOrAgencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyId', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placements.jobdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(default='fresher', max_length=500)),
                ('qualification', models.CharField(default='BE', max_length=400)),
                ('skills', models.CharField(default='HTML', max_length=600)),
                ('city', models.CharField(default='Hubli', max_length=500)),
                ('expected_salary', models.CharField(max_length=300)),
                ('resume', models.FileField(upload_to='applied_resume/')),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.jobdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
