# Generated by Django 4.2.6 on 2024-01-08 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_companyjobsaved_appliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default='BCA', max_length=300)),
                ('experience', models.CharField(default='fresher', max_length=300)),
                ('skills', models.CharField(default='html', max_length=400)),
                ('DOB', models.CharField(max_length=100)),
                ('about', models.CharField(default='Passionate professional dedicated to driving innovation and fostering growth through collaboration and strategic expertise.', max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
