# Generated by Django 4.1.7 on 2024-01-08 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='data analyst', max_length=300)),
                ('job_description', models.CharField(default='abc', max_length=1000)),
                ('location', models.CharField(default='hubli', max_length=300)),
                ('work_mode', models.CharField(default='work from office', max_length=100)),
                ('no_of_vacancy', models.CharField(default='2', max_length=100)),
                ('mandatory_skills', models.CharField(default='HTML', max_length=500)),
                ('optional_skills', models.CharField(default='C', max_length=500)),
                ('internship_type', models.CharField(default='3LPA', max_length=400)),
                ('qualification', models.CharField(default='BCA', max_length=300)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=10)),
                ('job_type', models.CharField(default='Full time', max_length=100)),
                ('country', models.CharField(default='India', max_length=300)),
                ('state', models.CharField(default='Karnataka', max_length=300)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
