# Generated by Django 4.1.7 on 2024-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0008_internships_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='type',
            field=models.CharField(default='job', max_length=300),
        ),
        migrations.DeleteModel(
            name='Internships',
        ),
    ]
