# Generated by Django 4.1.7 on 2024-01-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0009_jobdetails_type_delete_internships'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='type',
            new_name='J_type',
        ),
    ]
