# Generated by Django 4.1.7 on 2024-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0010_rename_type_jobdetails_j_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
