# Generated by Django 4.2.6 on 2024-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0011_appliedjobs_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(max_length=255, upload_to='uploads/')),
            ],
        ),
    ]
