# Generated by Django 4.2.6 on 2024-03-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0013_newuser_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=700)),
                ('email', models.CharField(default='email', max_length=700)),
                ('message', models.CharField(default='message', max_length=700)),
            ],
        ),
    ]
