# Generated by Django 4.2.6 on 2024-03-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0014_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='expected_salary',
        ),
    ]
