# Generated by Django 4.2.6 on 2024-03-31 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0015_remove_appliedjobs_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='date', max_length=700)),
                ('start_time', models.CharField(default='start time', max_length=700)),
                ('end_time', models.CharField(default='end time', max_length=700)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
