# Generated by Django 4.2.6 on 2024-03-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0016_selectedtiming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedTiming',
            new_name='AvailableTiming',
        ),
    ]
