# Generated by Django 4.2.6 on 2024-03-31 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0017_rename_selectedtiming_availabletiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('start_time', models.CharField(default='Pending', max_length=200)),
                ('end_time', models.CharField(default='Pending', max_length=200)),
                ('mode_of_interview', models.CharField(default='Office', max_length=500)),
                ('confirmation', models.CharField(default='Pending', max_length=200)),
                ('user_confirmation', models.BooleanField(default=0)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.appliedjobs')),
                ('company_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
