# Generated by Django 4.2.6 on 2024-03-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0018_scheduleinterview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleinterview',
            old_name='company_id_id',
            new_name='user_id',
        ),
    ]
