# Generated by Django 4.2.6 on 2024-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0020_alter_newuser_city_alter_newuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='is_promoting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='job_link',
            field=models.CharField(default='job link', max_length=700),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='profile',
            field=models.ImageField(default='company logo', upload_to='uploaded_images/'),
        ),
    ]
