# Generated by Django 4.2.6 on 2024-04-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0021_jobdetails_is_promoting_jobdetails_job_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='profile',
            new_name='company_profile',
        ),
    ]
